# -*- coding: utf-8 -*-
"""SA_New_Resident_Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123lwNXYPbLaxxjB1HWNQUzNeXxj3VG7b

# 🏙️ San Antonio New Resident Agent
**Unified Utility Setup for CPS Energy ⚡ · SAWS Water 💧 · City of SA 🏛️**

This notebook guides new San Antonio residents through utility enrollment with:
- 🤖 AI-powered Q&A chat connected to SA Resident Agent Backend
- 📋 Multi-step validated forms for all 3 services
- ✅ Live progress checklist synced to backend
- 💾 Session data saved to JSON

---
### Setup — complete Cell 2 before running anything else
1. Make sure the backend is running at http://localhost:8000
2. Make sure the crawler/AI server is running at http://localhost:8001
3. Run all cells top to bottom
"""

# ── Cell 1 · Install dependencies ─────────────────────────────────────────────
import subprocess
subprocess.run(["pip", "install", "ipywidgets", "requests", "--quiet"])

from IPython.display import display, HTML, clear_output
import ipywidgets as widgets
import requests
import json, re, os
from datetime import datetime
print('✅ Dependencies ready')

# ── Cell 2 · Backend Configuration ────────────────────────────────────────────

import uuid
BACKEND_URL = "http://localhost:8000"
SESSION_ID  = str(uuid.uuid4())
USER_ID     = str(uuid.uuid4())
print(f'   Session ID: {SESSION_ID}')

# Test backend connection
try:
    r = requests.get(f"{BACKEND_URL}/", timeout=5)
    data = r.json()
    print(f'✅ Backend connected!')
    print(f'   Status : {data["status"]}')
    print(f'   Service: {data["service"]}')
except requests.exceptions.ConnectionError:
    print('❌ Backend not reachable — make sure docker compose is running in the backend folder')
except Exception as e:
    print(f'❌ Error: {e}')

# Test AI agent connection (through backend)
try:
    r = requests.get(f"{BACKEND_URL}/api/services/cps", timeout=5)
    print(f'✅ Services endpoint ready')
except Exception as e:
    print(f'⚠️  Services endpoint error: {e}')

# ── Cell 3 · Service & Form Definitions ───────────────────────────────────────
SERVICES = {
    'cps': {
        'name': 'CPS Energy', 'icon': '⚡', 'desc': 'Electric service setup',
        'steps': [
            {
                'title': 'Personal Information',
                'fields': [
                    {'id': 'firstName',  'label': 'First Name',        'type': 'text',   'required': True,  'placeholder': 'Maria'},
                    {'id': 'lastName',   'label': 'Last Name',         'type': 'text',   'required': True,  'placeholder': 'Garcia'},
                    {'id': 'ssn',        'label': 'Last 4 of SSN',     'type': 'text',   'required': True,  'placeholder': '1234',
                     'hint': 'Used for identity verification', 'maxlen': 4, 'pattern': r'^\d{4}$'},
                    {'id': 'dob',        'label': 'Date of Birth',     'type': 'date',   'required': True},
                ]
            },
            {
                'title': 'Service Address',
                'fields': [
                    {'id': 'address',    'label': 'Street Address',    'type': 'text',   'required': True,  'placeholder': '1234 Main St'},
                    {'id': 'apt',        'label': 'Apt / Unit',        'type': 'text',   'required': False, 'placeholder': 'Apt 2B'},
                    {'id': 'zip',        'label': 'ZIP Code',          'type': 'text',   'required': True,  'placeholder': '78201',
                     'maxlen': 5, 'pattern': r'^\d{5}$'},
                    {'id': 'moveInDate', 'label': 'Move-in Date',      'type': 'date',   'required': True},
                ]
            },
            {
                'title': 'Contact & Plan',
                'fields': [
                    {'id': 'email',      'label': 'Email Address',     'type': 'email',  'required': True,  'placeholder': 'you@email.com'},
                    {'id': 'phone',      'label': 'Phone Number',      'type': 'tel',    'required': True,  'placeholder': '(210) 555-0100'},
                    {'id': 'plan',       'label': 'Rate Plan',         'type': 'select', 'required': True,
                     'options': ['Standard Residential', 'Budget Billing', 'Time-of-Use (TOU)', 'Green Power Option']},
                    {'id': 'paperless',  'label': 'Paperless Billing', 'type': 'select', 'required': True,
                     'options': ['Yes — email only', 'No — mail statements']},
                ]
            },
        ]
    },
    'saws': {
        'name': 'SAWS Water', 'icon': '💧', 'desc': 'Water & sewer account',
        'steps': [
            {
                'title': 'Account Holder',
                'fields': [
                    {'id': 'firstName',  'label': 'First Name',        'type': 'text',   'required': True,  'placeholder': 'Maria'},
                    {'id': 'lastName',   'label': 'Last Name',         'type': 'text',   'required': True,  'placeholder': 'Garcia'},
                    {'id': 'idType',     'label': 'ID Type',           'type': 'select', 'required': True,
                     'options': ["Driver's License", 'State ID', 'Passport', 'Military ID']},
                    {'id': 'idNumber',   'label': 'ID Number',         'type': 'text',   'required': True,  'placeholder': 'TX12345678'},
                ]
            },
            {
                'title': 'Service Address',
                'fields': [
                    {'id': 'address',    'label': 'Street Address',    'type': 'text',   'required': True,  'placeholder': '1234 Main St'},
                    {'id': 'zip',        'label': 'ZIP Code',          'type': 'text',   'required': True,  'placeholder': '78201',
                     'maxlen': 5, 'pattern': r'^\d{5}$'},
                    {'id': 'propType',   'label': 'Property Type',     'type': 'select', 'required': True,
                     'options': ['Single Family', 'Apartment / Condo', 'Mobile Home', 'Duplex']},
                    {'id': 'startDate',  'label': 'Service Start Date','type': 'date',   'required': True},
                ]
            },
            {
                'title': 'Billing Preferences',
                'fields': [
                    {'id': 'email',      'label': 'Billing Email',     'type': 'email',  'required': True,  'placeholder': 'you@email.com'},
                    {'id': 'phone',      'label': 'Phone Number',      'type': 'tel',    'required': True,  'placeholder': '(210) 555-0100'},
                    {'id': 'autopay',    'label': 'AutoPay',           'type': 'select', 'required': True,
                     'options': ['Enroll in AutoPay', 'Manual payments']},
                    {'id': 'assistance', 'label': 'Low-Income Assistance?', 'type': 'select', 'required': False,
                     'options': ['No', 'Yes — apply for SAWS Cares']},
                ]
            },
        ]
    },
    'city': {
        'name': 'City of SA', 'icon': '🏛️', 'desc': 'Permits & city registration',
        'steps': [
            {
                'title': 'Resident Registration',
                'fields': [
                    {'id': 'firstName',  'label': 'First Name',        'type': 'text',   'required': True,  'placeholder': 'Maria'},
                    {'id': 'lastName',   'label': 'Last Name',         'type': 'text',   'required': True,  'placeholder': 'Garcia'},
                    {'id': 'email',      'label': 'Email Address',     'type': 'email',  'required': True,  'placeholder': 'you@email.com'},
                    {'id': 'phone',      'label': 'Phone Number',      'type': 'tel',    'required': True,  'placeholder': '(210) 555-0100'},
                ]
            },
            {
                'title': 'Home Address',
                'fields': [
                    {'id': 'address',    'label': 'Street Address',    'type': 'text',   'required': True,  'placeholder': '1234 Main St'},
                    {'id': 'zip',        'label': 'ZIP Code',          'type': 'text',   'required': True,  'placeholder': '78201',
                     'maxlen': 5, 'pattern': r'^\d{5}$'},
                    {'id': 'district',   'label': 'Council District',  'type': 'select', 'required': False,
                     'options': ['Not sure','District 1','District 2','District 3','District 4',
                                 'District 5','District 6','District 7','District 8','District 9','District 10']},
                    {'id': 'residency',  'label': 'Residency Type',    'type': 'select', 'required': True,
                     'options': ['Renter', 'Homeowner', 'Moving in']},
                ]
            },
            {
                'title': 'City Services',
                'fields': [
                    {'id': 'trash',      'label': 'Trash Pickup Day',  'type': 'select', 'required': True,
                     'options': ['Monday','Tuesday','Wednesday','Thursday','Friday']},
                    {'id': 'recycling',  'label': 'Recycling Bin',     'type': 'select', 'required': True,
                     'options': ['Small (18 gal)', 'Large (96 gal)']},
                    {'id': 'voterReg',   'label': 'Voter Registration', 'type': 'select', 'required': False,
                     'options': ['Already registered', 'Register now via VOTE.ORG', 'Skip for now']},
                    {'id': 'alerts',     'label': 'City Alerts',       'type': 'select', 'required': False,
                     'options': ['Opt in', 'Opt out']},
                ]
            },
        ]
    },
}

# Session state — shared across all cells
session = {
    'completed':    {},
    'chat_history': [],
    'agent_checklist': {},
}

print('✅ Service definitions loaded')

# ── Cell 4 · Validation Helpers ───────────────────────────────────────────────
def validate_field(field, value):
    """Returns an error string, or None if valid."""
    v = value.strip()
    if field.get('required') and not v:
        return f"{field['label']} is required"
    if not v:
        return None
    pattern = field.get('pattern')
    if pattern and not re.match(pattern, v):
        if field['id'] == 'ssn': return 'Enter exactly 4 digits'
        if field['id'] == 'zip': return 'Enter a valid 5-digit ZIP'
        return 'Invalid format'
    if field['type'] == 'email':
        if not re.match(r'^[^\s@]+@[^\s@]+\.[^\s@]+$', v):
            return 'Enter a valid email address'
    if field['type'] == 'tel':
        if len(re.sub(r'\D', '', v)) < 7:
            return 'Enter a valid phone number'
    return None

def validate_step(fields, data):
    """Returns {field_id: error_msg}. Empty dict means all fields are valid."""
    return {f['id']: e for f in fields if (e := validate_field(f, data.get(f['id'], '')))}

print('✅ Validators ready')

# ── Cell 5 · AI Chat Engine (connected to SA Resident Agent Backend) ──────────

def chat_with_agent(user_message):
    """Send a message to the backend AI agent and get a RAG-grounded response."""
    session['chat_history'].append({'role': 'user', 'content': user_message})

    try:
        response = requests.post(
            f"{BACKEND_URL}/api/services/agent/chat",
            json={"session_id": SESSION_ID, "message": user_message},
            timeout=30
        )
        response.raise_for_status()
        data = response.json()
        reply = data["data"]["reply"]

        # Sync checklist state from agent response
        if "checklist" in data["data"]:
            session['agent_checklist'] = data["data"]["checklist"]

    except requests.exceptions.ConnectionError:
        reply = "⚠️ Backend not reachable. Make sure docker compose is running at localhost:8000"
    except requests.exceptions.Timeout:
        reply = "⚠️ Request timed out. The AI agent may be busy — try again."
    except Exception as e:
        reply = f"⚠️ Error: {str(e)}"

    session['chat_history'].append({'role': 'assistant', 'content': reply})
    return reply

def submit_form_to_backend(service_id, form_data):
    """Submit completed form data to the backend."""
    try:
        response = requests.post(
            f"{BACKEND_URL}/api/services/submit/{service_id}",
            json={"user_id": USER_ID, "service": service_id, "form_data": form_data},
            timeout=15
        )
        response.raise_for_status()
        return response.json()
    except Exception as e:
        return {"status": "error", "detail": str(e)}

def sync_checklist_to_backend(service_id, step, completed):
    """Sync form completion status to the backend checklist."""
    try:
        requests.patch(
            f"{BACKEND_URL}/api/checklist/{USER_ID}",
            json={"service": service_id, "step": step, "completed": completed},
            timeout=10
        )
    except Exception as e:
        print(f"⚠️ Checklist sync failed: {e}")

print('✅ Backend-connected chat engine ready')

# ── Cell 6 · Progress Dashboard ───────────────────────────────────────────────
def show_progress():
    """Render a styled HTML progress dashboard for all 3 services."""
    done = session['completed']
    pct  = int(len(done) / 3 * 100)

    rows_html = ''
    for sid, svc in SERVICES.items():
        if sid in done:
            status = '<span style="color:#20b2a0;font-weight:600">✅ Complete</span>'
            detail_parts = []
            for step in svc['steps']:
                for f in step['fields']:
                    val = done[sid].get(f['id'], '')
                    if val and f['id'] != 'ssn':
                        detail_parts.append(
                            f'<span style="margin-right:14px;font-size:11px;color:#94a8bc">'
                            f'<b style="color:#c8d8e8">{f["label"]}:</b> {val}</span>'
                        )
            summary = f'<div style="margin-top:6px;line-height:2">{" ".join(detail_parts)}</div>'
        else:
            status  = '<span style="color:#f5a623">⏳ Pending</span>'
            summary = ''

        rows_html += f'''
          <tr style="border-bottom:1px solid rgba(255,255,255,0.06)">
            <td style="padding:12px 14px;font-size:22px;vertical-align:top">{svc["icon"]}</td>
            <td style="padding:12px 8px;vertical-align:top">
              <div style="font-weight:600;color:#e8edf2">{svc["name"]}</div>
              <div style="font-size:12px;color:#7a8fa6">{svc["desc"]}</div>
              {summary}
            </td>
            <td style="padding:12px 14px;text-align:right;vertical-align:top;white-space:nowrap">{status}</td>
          </tr>'''

    all_done_banner = ''
    if pct == 100:
        all_done_banner = '''
          <div style="text-align:center;padding:16px 0 4px;color:#20b2a0;
                      font-size:15px;font-weight:600">🎉 All services complete! Welcome to San Antonio!</div>'''

    display(HTML(f'''
    <div style="font-family:\'Segoe UI\',system-ui,sans-serif;background:#0d1b2e;
                border-radius:14px;padding:24px;margin:6px 0;
                border:1.5px solid rgba(255,255,255,0.08)">
      <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:18px">
        <div style="font-size:17px;font-weight:700;color:#e8edf2">🏙️ SA New Resident Setup</div>
        <div style="font-size:13px;color:#20b2a0;font-weight:600">{pct}% Complete</div>
      </div>
      <div style="background:rgba(255,255,255,0.08);border-radius:999px;height:8px;margin-bottom:20px">
        <div style="background:#20b2a0;height:8px;border-radius:999px;width:{pct}%"></div>
      </div>
      <table style="width:100%;border-collapse:collapse">{rows_html}</table>
      {all_done_banner}
    </div>
    <div style="font-family:\'Segoe UI\',system-ui,sans-serif;background:#1a1200;
                border:1px solid rgba(245,166,35,0.25);border-radius:10px;
                padding:14px 18px;margin-top:8px">
      <div style="font-size:12px;font-weight:600;color:#f5a623;margin-bottom:8px">📋 Documents to have ready</div>
      <div style="font-size:12px;color:#94a8bc;line-height:2.2">
        › Photo ID or Passport &nbsp;·&nbsp;
        › SSN last 4 digits <em>(CPS Energy only)</em> &nbsp;·&nbsp;
        › New SA street address &nbsp;·&nbsp;
        › Move-in date &nbsp;·&nbsp;
        › Email address
      </div>
    </div>'''))

show_progress()

print('Completed services:', list(session['completed'].keys()))
print('Session data:', session['completed'])

# ── Cell 7 · AI Chat Interface ────────────────────────────────────────────────
chat_out   = widgets.Output()
chat_input = widgets.Text(
    placeholder='Ask about rates, documents, timelines, plans...',
    layout=widgets.Layout(width='500px')
)
ask_btn = widgets.Button(
    description='Ask →',
    style={'button_color': '#1a8f7e'},
    layout=widgets.Layout(width='90px')
)
quick_btns = [
    widgets.Button(description=q,
                   style={'button_color': '#162438'},
                   layout=widgets.Layout(width='auto'))
    for q in [
        'What documents do I need?',
        'How long does CPS setup take?',
        'Average water bill?',
        'Is there a deposit required?',
        'Tell me about SAWS Cares',
    ]
]
quick_box = widgets.HBox(quick_btns,
                          layout=widgets.Layout(flex_wrap='wrap', gap='6px', margin='6px 0'))

def render_chat():
    with chat_out:
        clear_output(wait=True)
        html = ('<div style="font-family:\'Segoe UI\',system-ui,sans-serif;'
                'max-height:360px;overflow-y:auto;padding:4px">')
        if not session['chat_history']:
            html += ('<div style="color:#7a8fa6;font-size:13px;padding:14px">'
                     '👋 Welcome! Ask me anything about San Antonio utility setup.</div>')
        for msg in session['chat_history']:
            if msg['role'] == 'user':
                html += (f'<div style="text-align:right;margin:8px 0">'
                         f'<span style="background:#1a8f7e;color:white;padding:8px 14px;'
                         f'border-radius:14px 14px 4px 14px;font-size:13px;'
                         f'display:inline-block;max-width:78%">{msg["content"]}</span></div>')
            else:
                content = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', msg['content'])
                content = content.replace('\n', '<br>')
                html += (f'<div style="margin:8px 0">'
                         f'<span style="background:rgba(255,255,255,0.06);'
                         f'border:1px solid rgba(255,255,255,0.08);color:#e8edf2;'
                         f'padding:9px 14px;border-radius:14px 14px 14px 4px;'
                         f'font-size:13px;display:inline-block;max-width:82%;line-height:1.65">'
                         f'🤖 {content}</span></div>')
        html += '</div>'
        display(HTML(html))

def on_ask(b=None):
    msg = chat_input.value.strip()
    if not msg:
        return
    chat_input.value = ''
    with chat_out:
        clear_output(wait=True)
        display(HTML('<div style="color:#94a8bc;font-size:12px;padding:10px">'
                     '⏳ SA Resident Agent is thinking...</div>'))
    try:
        chat_with_agent(msg)
    except Exception as exc:
        session['chat_history'].append({
            'role': 'assistant',
            'content': f'⚠️ Error: {exc}'
        })
    render_chat()

def on_quick(b):
    chat_input.value = b.description
    on_ask()

ask_btn.on_click(on_ask)
chat_input.on_submit(on_ask)
for btn in quick_btns:
    btn.on_click(on_quick)

render_chat()
display(widgets.VBox([
    chat_out,
    widgets.HBox([chat_input, ask_btn]),
    quick_box,
]))

# ── Cell 8 · Form Engine ──────────────────────────────────────────────────────
def make_form(service_id):
    svc   = SERVICES[service_id]
    steps = svc['steps']
    state = {'step': 0, 'data': {s['title']: {} for s in steps}}

    main_out   = widgets.Output()
    status_out = widgets.Output()

    def render_step():
        idx   = state['step']
        step  = steps[idx]
        total = len(steps)

        dots = ''.join(
            f'<span style="display:inline-block;width:28px;height:28px;border-radius:50%;'
            f'background:{"#20b2a0" if i <= idx else "rgba(255,255,255,0.1)"};'
            f'color:white;text-align:center;line-height:28px;'
            f'font-size:12px;font-weight:600;margin:0 3px">'
            f'{"✓" if i < idx else i + 1}</span>'
            for i in range(total)
        )
        header = widgets.HTML(value=f'''
        <div style="font-family:'Segoe UI',system-ui,sans-serif;background:#0d1b2e;
                    border-radius:12px;padding:20px 22px;
                    border:1.5px solid rgba(255,255,255,0.08);margin-bottom:10px">
          <div style="margin-bottom:14px">
            <span style="font-size:22px">{svc["icon"]}</span>
            <span style="font-size:16px;font-weight:700;color:#e8edf2;margin-left:10px">{svc["name"]}</span>
            <span style="font-size:12px;color:#7a8fa6;margin-left:8px">— {step["title"]}</span>
          </div>
          <div style="margin-bottom:8px">{dots}</div>
          <div style="font-size:11px;color:#7a8fa6">Step {idx + 1} of {total}</div>
        </div>''')

        field_widgets = {}
        saved = state['data'].get(step['title'], {})
        field_items = []

        for f in step['fields']:
            req_star  = ' <span style="color:#f5a623">*</span>' if f.get('required') else ''
            hint_html = (f'<div style="font-size:11px;color:#7a8fa6;margin-top:2px">{f["hint"]}</div>'
                         if f.get('hint') else '')
            label = widgets.HTML(value=
                f'<div style="font-size:12px;font-weight:600;color:#94a8bc;'
                f'margin-top:10px;margin-bottom:4px">{f["label"]}{req_star}</div>'
                f'{hint_html}'
            )
            prev = saved.get(f['id'], '')
            if f['type'] == 'select':
                opts = [''] + f['options']
                w = widgets.Dropdown(
                    options=opts,
                    value=prev if prev in opts else '',
                    layout=widgets.Layout(width='380px')
                )
            elif f['type'] == 'date':
                w = widgets.DatePicker(layout=widgets.Layout(width='220px'))
            else:
                w = widgets.Text(
                    value=prev,
                    placeholder=f.get('placeholder', ''),
                    layout=widgets.Layout(width='380px')
                )
            field_widgets[f['id']] = (f, w)
            field_items.append(widgets.VBox([label, w]))

        back_btn = widgets.Button(
            description='← Previous' if idx > 0 else '✕ Cancel',
            layout=widgets.Layout(width='130px', height='36px'),
            style={'button_color': '#162438'}
        )
        next_btn = widgets.Button(
            description='Submit ✓' if idx == total - 1 else 'Next →',
            layout=widgets.Layout(width='130px', height='36px'),
            style={'button_color': '#1a8f7e'}
        )
        nav = widgets.HBox(
            [back_btn, next_btn],
            layout=widgets.Layout(margin='16px 0 8px 0', gap='10px')
        )

        def on_next(b, fw=field_widgets, s=step, i=idx):
            data = {}
            for fid, (field, w) in fw.items():
                data[fid] = str(w.value) if w.value else ''
            errors = validate_step(s['fields'], data)
            with status_out:
                clear_output(wait=True)
                if errors:
                    err_html = ('<div style="background:rgba(226,75,74,0.12);'
                                'border:1px solid rgba(226,75,74,0.3);'
                                'border-radius:8px;padding:12px;margin:4px 0">')
                    for _, msg in errors.items():
                        err_html += f'<div style="font-size:12px;color:#e24b4a;padding:2px 0">⚠ {msg}</div>'
                    err_html += '</div>'
                    display(HTML(err_html))
                    return
            state['data'][s['title']].update(data)
            with status_out:
                clear_output()
            if state['step'] < total - 1:
                state['step'] += 1
                with main_out:
                    clear_output(wait=True)
                    display(render_step())
            else:
                flat = {k: v for d in state['data'].values() for k, v in d.items()}
                session['completed'][service_id] = flat

                # Sync to backend
                result = submit_form_to_backend(service_id, flat)
                sync_checklist_to_backend(service_id, "account", True)
                sync_checklist_to_backend(service_id, "billing", True)
                sync_checklist_to_backend(service_id, "docs", True)

                status_msg = "synced to backend ✅" if result.get("status") == "success" else "saved locally"
                with main_out:
                    clear_output(wait=True)
                    display(widgets.HTML(value=f'''
                    <div style="font-family:'Segoe UI',system-ui,sans-serif;
                                background:#0d1b2e;border-radius:12px;padding:30px;
                                text-align:center;
                                border:1.5px solid rgba(32,178,160,0.35)">
                      <div style="font-size:48px;margin-bottom:12px">🎉</div>
                      <div style="font-size:18px;font-weight:700;color:#20b2a0;margin-bottom:8px">
                        {svc["name"]} Submitted!
                      </div>
                      <div style="font-size:13px;color:#7a8fa6;line-height:1.7">
                        Your application has been recorded and {status_msg}.<br>
                        Re-run <b style="color:#e8edf2">Cell 6</b> to update the progress dashboard.
                      </div>
                    </div>'''))

        def on_back(b):
            with status_out:
                clear_output()
            if state['step'] > 0:
                state['step'] -= 1
                with main_out:
                    clear_output(wait=True)
                    display(render_step())

        next_btn.on_click(on_next)
        back_btn.on_click(on_back)

        return widgets.VBox(
            [header] + field_items + [nav],
            layout=widgets.Layout(padding='4px')
        )

    with main_out:
        display(render_step())

    display(widgets.VBox([main_out, status_out]))

print('✅ Form engine ready')

# ── Cell 9 · ⚡ CPS Energy Form ───────────────────────────────────────────────
make_form('cps')

print('Completed services:', list(session['completed'].keys()))

# ── Cell 10 · 💧 SAWS Water Form ──────────────────────────────────────────────
make_form('saws')

# ── Cell 11 · 🏛️ City of SA Form ─────────────────────────────────────────────
make_form('city')

# ── Cell 12 · 💾 Save Session Data ────────────────────────────────────────────
if session['completed']:
    fname = f"sa_resident_data_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    output = {
        'saved_at':           datetime.now().isoformat(),
        'backend_url':        BACKEND_URL,
        'session_id':         SESSION_ID,
        'completed_services': list(session['completed'].keys()),
        'forms': {
            SERVICES[sid]['name']: {k: ('****' if k == 'ssn' else v)
                                    for k, v in data.items()}
            for sid, data in session['completed'].items()
        }
    }
    with open(fname, 'w') as f:
        json.dump(output, f, indent=2, default=str)
    print(f'✅ Saved → {fname}')
    print(f'   Services: {", ".join(output["completed_services"])}')
    print( '   SSN redacted.')

    # Sync all completed forms to backend
    print('\nSyncing to backend...')
    for service_id, form_data in session['completed'].items():
        result = submit_form_to_backend(service_id, form_data)
        print(f'   {service_id}: {result.get("status", "unknown")}')
else:
    print('No completed forms yet — finish at least one service form first.')

# ── Cell 13 · 📊 Final Progress Dashboard ─────────────────────────────────────
show_progress()